In [1]:
import numpy as np

In [6]:
arr1 = np.array([1,3,5,7,9])

In [7]:
arr1

array([1, 3, 5, 7, 9])

In [8]:
type(arr1)

numpy.ndarray

In [9]:
arr2 = np.array([2,4,6,8,10])

In [10]:
arr2

array([ 2,  4,  6,  8, 10])

In [12]:
arr3 = arr1 + arr2

In [13]:
arr3

array([ 3,  7, 11, 15, 19])

In [16]:
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr = np.array([[1,2,3,5], [4,7,6,8]])

In [19]:
arr

array([[1, 2, 3, 5],
       [4, 7, 6, 8]])

In [20]:
type(arr)

numpy.ndarray

In [22]:
arr.shape

(2, 4)