In [1]:
import numpy as np

In [2]:
!pip install numpy

In [3]:
arr = np.array([1,2,3,4])

In [4]:
arr

array([1, 2, 3, 4])

In [7]:
# 2D Array
arr2 = np.array([[1,2,4], [5,6,7]])

In [8]:
arr2

array([[1, 2, 4],
       [5, 6, 7]])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.full((4,6), 8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [14]:
# Identity Matrix using numpy
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.arange(1, 100, 9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [16]:
np.arange(0,50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [17]:
np.linspace(1, 100, 4)

array([  1.,  34.,  67., 100.])

In [18]:
np.linspace(1, 100, 5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [19]:
myarr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

In [21]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [22]:
myarr.shape

(4, 3)

In [23]:
myarr.size

12

In [24]:
myarr.ndim

2

In [25]:
myarr.dtype

dtype('int64')

In [26]:
myarr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]], dtype='float32')

In [28]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [31]:
n = myarr.astype('float64')

In [32]:
n

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [33]:
n.dtype

dtype('float64')

In [34]:
myarr.dtype

dtype('float32')

In [35]:
myarr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

In [36]:
myarr.shape

(4, 3)

In [37]:
reshapped = myarr.reshape((3,4))

In [38]:
reshapped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [40]:
myarr.reshape((2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [41]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [43]:
flatarr = myarr.flatten()

In [44]:
flatarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [45]:
flatarr.shape

(12,)

In [46]:
flatarr.ndim

1