In [1]:
import numpy as np

In [2]:
arr = np.array([[1,3,4], [2,5,6], [7,8,9], [11,12,13]])

In [3]:
arr

array([[ 1,  3,  4],
       [ 2,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [4]:
print(arr[0])

[1 3 4]


In [5]:
print(arr[0][0])

1


In [6]:
for i in arr:
    print(i)

[1 3 4]
[2 5 6]
[7 8 9]
[11 12 13]


In [8]:
for i in arr:
    for t in i:
        print(t)

1
3
4
2
5
6
7
8
9
11
12
13


In [9]:
flat = arr.flatten()

In [10]:
flat

array([ 1,  3,  4,  2,  5,  6,  7,  8,  9, 11, 12, 13])

In [11]:
flat[0:3]

array([1, 3, 4])

In [12]:
flat[3:6]

array([2, 5, 6])

In [13]:
flat[:5]

array([1, 3, 4, 2, 5])

In [18]:
flat[-6:-1]

array([ 7,  8,  9, 11, 12])

In [19]:
flat[::2]

array([ 1,  4,  5,  7,  9, 12])

In [20]:
flat

array([ 1,  3,  4,  2,  5,  6,  7,  8,  9, 11, 12, 13])

In [22]:
b = arr[3:5]

In [23]:
b

array([[11, 12, 13]])

In [24]:
b[0] = 3333

In [25]:
b

array([[3333, 3333, 3333]])

In [26]:
arr

array([[   1,    3,    4],
       [   2,    5,    6],
       [   7,    8,    9],
       [3333, 3333, 3333]])

In [27]:
arr[3] = 24

In [28]:
arr


array([[ 1,  3,  4],
       [ 2,  5,  6],
       [ 7,  8,  9],
       [24, 24, 24]])

In [29]:
b = flat[2:5]

In [30]:
b

array([4, 2, 5])

In [31]:
b[0] = 24

In [32]:
b

array([24,  2,  5])

In [33]:
flat

array([ 1,  3, 24,  2,  5,  6,  7,  8,  9, 11, 12, 13])

In [37]:
b = flat[5:8].copy()

In [38]:
b

array([6, 7, 8])

In [39]:
b[0] = 100

In [40]:
b

array([100,   7,   8])

In [41]:
flat

array([ 1,  3, 24,  2,  5,  6,  7,  8,  9, 11, 12, 13])

In [42]:
flat[[3,5,7]]

array([2, 6, 8])

In [43]:
arr = [arr > 10]

In [44]:
arr

[array([[False, False, False],
        [False, False, False],
        [False, False, False],
        [ True,  True,  True]])]

In [45]:
arr

[array([[False, False, False],
        [False, False, False],
        [False, False, False],
        [ True,  True,  True]])]

In [46]:
flat

array([ 1,  3, 24,  2,  5,  6,  7,  8,  9, 11, 12, 13])

In [47]:
flat[flat > 10]

array([24, 11, 12, 13])

In [48]:
flat[flat > 11]

array([24, 12, 13])