# Multidimensional Indexing and Axis using numpy

In [1]:
import numpy as np

In [7]:
arr = np.array([[1, 2, 3],
               [4, 5, 6], 
               [7, 8, 9]])

In [8]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr[0]

array([1, 2, 3])

In [10]:
arr[1]

array([4, 5, 6])

In [11]:
arr[0][2]

3

In [12]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [13]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [14]:
arr[0, 2]

3

In [15]:
arr[0:3, 1:2]

array([[2],
       [5],
       [8]])

In [18]:
arr[0:3, 0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr[0:3, 1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [20]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])