# Data Types in numpy

In [1]:
import numpy as np

In [9]:
arr = np.array([23, 5, 42, 19])

In [10]:
arr.dtype

dtype('int64')

In [4]:
arr.astype('float64')

array([23.,  5., 42., 19.])

In [5]:
arr

array([23,  5, 42, 19])

In [6]:
arr.dtype

dtype('int64')

In [15]:
arr2 = np.array([23, 5, 42, 19], dtype='float32')

In [16]:
arr2

array([23.,  5., 42., 19.], dtype=float32)

In [17]:
arr.nbytes

32

In [18]:
arr2.nbytes

16